### ISSUE TITLE
Unused DepersonalizeChecker plugin

### ISSUE THREAD

**Issue by sshymko** [yireo/Yireo_DisableLog2#1]
The source code contains the plugin `Yireo\DisableLog2\Plugin\PageCache\DepersonalizeChecker`, but it is not registered in `di.xml` or anywhere else. The plugin needs to be either activated or removed as unnecessary.

It is no clear whether the plugin is safe to use or not. For instance, the original implementation of `\Magento\PageCache\Model\DepersonalizeChecker::checkIfDepersonalize()` returns `false` for non-cacheable and AJAX requests, but the plugin always returns `true`.

**Comment by jissereitsma** [comment]
Thanks for spotting this. This was actually due to some experimenting. But in the end, I concluded that the Plugin was no longer needed. I will remove it from the source for clarity.
