### ISSUE TITLE
Error thrown when installing sample data with module installed

### ISSUE THREAD

**Issue by adamj88** [yireo/Yireo_DisableLog2#2]
When trying to install sample data using the Magento binary and the disable log module is installed (enabled or disabled) the below Exception is thrown.

Running: 
```
bin/magento sampledata:deploy`
```

Outputs:
```
  [Exception]
  Warning: file_get_contents(/vendor/yireo/magento2-disablelog2/source/composer.json): failed to open stream: No such file or directory in /vendor/magento/module-sample-data/Model/Dependency.php on line 109
```

When the `sampledata:deploy` method is being ran it adds requirements for it's modules in the root `composer.json` file and it reads all modules `composer.json` file in doing so. It looks as though Magento looks only in the same directory as the modules `registration.php` file.

**Comment by jissereitsma** [comment]
You are completely right. I started working on this right away and committed my changes, but only after I saw that you made a PR for this. I need coffee. I'll close your PR, but the same changes are now in a new release of this module 0.0.2.
