### ISSUE TITLE
Allow install on Magento 2.3.x?

### ISSUE THREAD

**Issue by cscd98** [yireo/Yireo_DisableLog2#7]
In composer.json, this needs changing to: "*":

"magento/framework": "^100.1.0|^101.0.0",

**Comment by jissereitsma** [comment]
Thanks for reporting. I have been late / lazy with making this work under Magento 2.3.x. A new release is now available. Please note that adding a wildcard with semantic versioning is absolutely not a good solution, so I would make sure not to recommend this anywhere: It will lead to numerous issues. Instead, for every major version, a module needs to be checked for correctness to prevent stuff from breaking. As of yet, the module is compatible with Magento 2.3. Let us know if this works for you too.

**Comment by cscd98** [comment]
@jissereitsma Thank you :+1:
